% Author: Atanu Giri
% Date: 12/11/2022
% This function finds the y axis limit for bar graph feature
function figureLimit = figureLimitFun(feature)
features = ["bigaccelerationperunittravel","bigjerkperunittravel", ...
    "approachavoidtimestamp","approachavoid","passingcentralzonerejectinitialpresence", ...
    "entrytime","exitTime","logicalApproach","velocitybeforetone", ...
    "distanceaftertoneuntillimitingtimestamp","velocityAfterToneUntilLimitingTimeStamp", ...
    "distancebeforetone","velocityaftertoneuntilentrytimestamp", ...
    "distanceafterentrytimestampuntillimitingtimestamp", ...
    "velocityafterentrytimestampuntillimitingtimestamp", ...
    "stoptimemethod6","effectivevelocitymethod6","rotationptsmethod1", ...
    "bigacceleration","jerkoutlierthreshold", ...
    "accoutlier_gesd_per_unittravel","stoppingpts_per_unittravel_method6", ...
    "rotationpts_per_unittravel_method4"];

featuresLimit = [30,10, ...
    20,1,1, ...
    15,50,1,0.25, ...
    4,0.25, ...
    0.5,0.5, ...
    4, ...
    0.5, ...
    18,0.5,10, ...
    40,200, ...
    20,400, ...
    3];

featureIndex = strcmpi(features,feature);
figureLimit = featuresLimit(featureIndex);
end